[server]
headless = true
port = 8501
address = "localhost"
enableCORS = false


[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0f62fe"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f4"
textColor = "#161616"
font = "IBM Plex Sans"
